add support for macFUSE FSKit backend, and modernize repo

diff --git a/syscallx/generate b/syscallx/generate
--- a/syscallx/generate
+++ b/syscallx/generate
@@ -1,34 +1,37 @@
 #!/bin/sh
 set -e
 
-mksys="$(go env GOROOT)/src/pkg/syscall/mksyscall.pl"
+goroot="$(go env GOROOT)"
+mksys="${goroot}/src/pkg/syscall/mksyscall.pl"
+if [ ! -f "$mksys" ]; then
+    mksys="${goroot}/src/syscall/mksyscall.pl"
+fi
+
+if [ ! -f "$mksys" ]; then
+    echo "mksyscall.pl not found under ${goroot}" >&2
+    exit 1
+fi
 
 fix() {
     sed 's,^package syscall$,&x\nimport "syscall",' \
 	| gofmt -r='BytePtrFromString -> syscall.BytePtrFromString' \
 	| gofmt -r='Syscall6 -> syscall.Syscall6' \
 	| gofmt -r='Syscall -> syscall.Syscall' \
+	| gofmt -r='errnoErr(a) -> syscall.Errno(a)' \
 	| gofmt -r='SYS_GETXATTR -> syscall.SYS_GETXATTR' \
 	| gofmt -r='SYS_LISTXATTR -> syscall.SYS_LISTXATTR' \
 	| gofmt -r='SYS_SETXATTR -> syscall.SYS_SETXATTR' \
 	| gofmt -r='SYS_REMOVEXATTR -> syscall.SYS_REMOVEXATTR' \
-	| gofmt -r='SYS_MSYNC -> syscall.SYS_MSYNC'
+	| gofmt -r='SYS_MSYNC -> syscall.SYS_MSYNC' \
+	| sed '/^\/\/go:build[[:space:]]*$/d'
 }
 
 cd "$(dirname "$0")"
 
-$mksys xattr_darwin.go \
+perl "$mksys" xattr_darwin.go \
     | fix \
-    >xattr_darwin_amd64.go
+    >xattr_darwin_syscall.go
 
-$mksys -l32 xattr_darwin.go \
+perl "$mksys" msync.go \
     | fix \
-    >xattr_darwin_386.go
-
-$mksys msync.go \
-    | fix \
-    >msync_amd64.go
-
-$mksys -l32 msync.go \
-    | fix \
-    >msync_386.go
+    >msync_syscall.go
